# app/config/main_paths.yaml

# ğŸ“„ CSVãƒ•ã‚¡ã‚¤ãƒ«é–¢é€£ãƒ‘ã‚¹
csv:
    receive_header_definition: 'infra/data_sources/master/receive_header_definition.csv' # ç¨®åˆ¥åˆ¤å®šç”¨ãƒ˜ãƒƒãƒ€ãƒ¼
    unit_price_table: 'infra/data_sources/master/costs/unit_price_table.csv'
    transport_costs: 'infra/data_sources/master/costs/transport_costs.csv'

# ğŸ“ ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªæ§‹æˆ
directories:
    input: 'infra/data_sources/input'
    output: 'infra/data_sources/output' # å‡ºåŠ›çµæœã®ä¿å­˜å…ˆ
    master_data: 'infra/data_sources/master' # ãƒã‚¹ã‚¿ãƒ¼CSVã®æ ¼ç´å ´æ‰€
    template: 'infra/data_sources/template'
    temp: 'infra/data_sources/temp' # ä¸€æ™‚ãƒ•ã‚¡ã‚¤ãƒ«æ ¼ç´

# ğŸ“œ ãƒ­ã‚°è¨­å®š
logs:
    app: 'logs/app.log'
    error: 'logs/error.log'
    debug: 'logs/debug.log'

# yamlãƒ‘ã‚¹
config_files:
    expected_dtypes: 'config/expected_import_csv_dtypes.yaml'
    required_columns_definition: 'config/required_columns_definition.yaml'
